In [1]:
import pandas as pd
import numpy as np

In [48]:
x=np.array([10,50])
y=np.array([30,40])
np.greater(x,y)

array([False,  True])

In [49]:
np.greater_equal(x,y)

array([False,  True])

In [50]:
np.less(x,y)

array([ True, False])

In [51]:
np.less_equal(x,y)

array([ True, False])

In [11]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 45, 28],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
    'Joining_Year': [2018, 2016, 2015, 2019, 2020]
}

In [12]:
data1=pd.DataFrame(data)
data1

Name  Age Department  Joining_Year
0    Alice   25         HR          2018
1      Bob   30         IT          2016
2  Charlie   35    Finance          2015
3    David   45         IT          2019
4      Eva   28         HR          2020

In [13]:
indexes=['A','B','C','D','E']
data1=pd.DataFrame(data,index=indexes)
data1

Name  Age Department  Joining_Year
A    Alice   25         HR          2018
B      Bob   30         IT          2016
C  Charlie   35    Finance          2015
D    David   45         IT          2019
E      Eva   28         HR          2020

In [27]:
data1.head(2)

Name  Age Department  Joining_Year
A  Alice   25         HR          2018
B    Bob   30         IT          2016

In [21]:
data1.columns

Index(['Name', 'Age', 'Department', 'Joining_Year'], dtype='object')

In [22]:
data1.dtypes

Name            object
Age              int64
Department      object
Joining_Year     int64
dtype: object

In [24]:
data1.describe()

Age  Joining_Year
count   5.000000      5.000000
mean   32.600000   2017.600000
std     7.829432      2.073644
min    25.000000   2015.000000
25%    28.000000   2016.000000
50%    30.000000   2018.000000
75%    35.000000   2019.000000
max    45.000000   2020.000000

In [80]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 45, 28],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
    'Joining_Year': [2018, 2016, 2015, 2019, 2020]
            }


In [81]:
df=pd.DataFrame(data)
df

Name  Age Department  Joining_Year
0    Alice   25         HR          2018
1      Bob   30         IT          2016
2  Charlie   35    Finance          2015
3    David   45         IT          2019
4      Eva   28         HR          2020

In [82]:
#Add a new column called Salary with values: [50000, 60000, 70000, 65000, 48000]
df['Salary']=[50000, 60000, 70000, 65000, 48000]
df

Name  Age Department  Joining_Year  Salary
0    Alice   25         HR          2018   50000
1      Bob   30         IT          2016   60000
2  Charlie   35    Finance          2015   70000
3    David   45         IT          2019   65000
4      Eva   28         HR          2020   48000

In [83]:
#Calculate a new column Experience as 2025 - Joining_Year.
df['Experience']=2025-df['Joining_Year']

In [84]:
# Define Seniority logic
def determine_seniority(exp):
    if exp < 5:
        return 'Junior'
    elif 5 <= exp < 8:
        return 'Mid'
    else:
        return 'Senior'

# Apply Seniority logic
df['Seniority'] = df['Experience'].apply(determine_seniority)

# Display the updated DataFrame
print(df)

      Name  Age Department  Joining_Year  Salary  Experience Seniority
0    Alice   25         HR          2018   50000           7       Mid
1      Bob   30         IT          2016   60000           9    Senior
2  Charlie   35    Finance          2015   70000          10    Senior
3    David   45         IT          2019   65000           6       Mid
4      Eva   28         HR          2020   48000           5       Mid


In [74]:
import numpy as np
p=[[1,0],[0,1]]
q=[[4,2],[1,3]]
print(np.dot(p,q))

[[4 2]
 [1 3]]
